home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /home/
    url(r'^$', views.index, name='index'),
]

hpc_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^results/', include('results.urls')),
        url(r'^$', include('home.urls')),
]

results/urls.py
from django.conf.urls import url
from . import views

app_name = 'results'

urlpatterns = [
    # /results/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /results/<setup_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

home/models.py
from django.db import models

# Create your models here.

results/models.py
from django.db import models


class Setup(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Run(models.Model):
    setup = models.ForeignKey(Setup, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    master_workers = models.IntegerField(default=0)
    node1_workers = models.IntegerField(default=0)
    node2_workers = models.IntegerField(default=0)
    node_swap_gb = models.IntegerField(default=0)
    cpu_time = models.FloatField(default=0)
    real_time = models.FloatField(default=0)

    def __str__(self):
            return self.name

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

results/views.py
from django.views import generic
from .models import Setup


class IndexView(generic.ListView):
    template_name = 'results/index.html'

    def get_queryset(self):
        return Setup.objects.all()


class DetailView(generic.DeleteView):
    model = Setup
    template_name = 'results/detail.html'

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} HPC {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:index' %}">HPC</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'results:index' %}">
                            <spac class="glyphicon glyphicon-cd" aria-hidden="true"></spac>&nbsp; Results
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <spac class="glyphicon glyphicon-plus" aria-hidden="true"></spac>&nbsp; Add Results
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <spac class="glyphicon glyphicon-off" aria-hidden="true"></spac>&nbsp; Logout
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block body %}

    <h1>Test home page</h1>

{% endblock %}

results/templates/results/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} HPC {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'results/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'results:index' %}">HPC</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'results:index' %}">
                            <spac class="glyphicon glyphicon-cd" aria-hidden="true"></spac>&nbsp; Results
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value=""> 
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <spac class="glyphicon glyphicon-plus" aria-hidden="true"></spac>&nbsp; Add Results
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <spac class="glyphicon glyphicon-off" aria-hidden="true"></spac>&nbsp; Logout
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

results/templates/results/detail.html
{% extends 'results/base.html' %}

{% block title %} SetUp Details {% endblock %}
{% block body %}
    <h1>{{ setup.name }}</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

        <table class="table">
            <thead>
                <tr>
                    <th>Master workers</th>
                    <th>Node1 workers</th>
                    <th>Node2 workers</th>
                    <th>Nodes SWAP [GB]</th>
                    <th>CPU time</th>
                    <th>Real time</th>
                </tr>
            </thead>
            <tbody>
                {% for run in setup.run_set.all %}
                    <tr>
                        <td>{{ run.master_workers }}</td>
                        <td>{{ run.node1_workers }}</td>
                        <td>{{ run.node2_workers }}</td>
                        <td>{{ run.node_swap_gb }}</td>
                        <td>{{ run.cpu_time }}</td>
                        <td>{{ run.real_time }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

{% endblock %}

results/templates/results/index.html
{% extends 'results/base.html' %}

{% block body %}

    <div class="row">
        {% for setup in object_list %}
            <div class="col">
                <a href="{% url 'results:detail' setup.id%}">
                    <center>
                    <img
                            src="https://www.raspberrypi.org/wp-content/uploads/2015/08/raspberry-pi-logo.png"
                            class="img-responsive"
                            alt="raspberry-pi-logo" width="64" height="64">
                    <h3>{{ setup.name }}</h3>
                        </center>
                </a>
            </div>
        {% endfor %}
    </div>

{% endblock %}